version: '3'
services:
  web:
    depends_on:
      - db
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    restart: always
    ports:
      - 80:8000

  db:
    image: postgres
    restart: always
    volumes:
    - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
     - 5432:5432