version: '3'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    restart: always
    ports:
      - 8000:8000
    networks:
      - outside

  db:
    image: postgres
    restart: always
#    volumes:
#    - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
     - 5432:5432
    networks:
      - outside

networks:
  outside:
    external:
      name: soym_net
            
       
