version: '3'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    restart: always
    ports:
      - 8000:8000
    networks:
      - outside

networks:
  outside:
    external:
      name: soym_net
            
       
