# Generated by Django 2.0 on 2017-12-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMiLed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=2000)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
