# Generated by Django 2.0 on 2017-12-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0003_deviceespconfig_deviceespstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceespconfig',
            name='led_bright',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deviceespstatus',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deviceespstatus',
            name='mq',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deviceespstatus',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
